name: WildSkript
version: 1.8.4
author: [Dzikoysk, Sitieno14]
website: https://www.dzikoysk.net/projects/wildskript/doc/
main: net.dzikoysk.wildskript.WildSkript
loadbefore: [Skript, skQuery, RandomSK]
